# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blog
email: me@dimi.io
description: > # this means to ignore newlines until "baseurl:"
  Dimitri Walters's blog
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://dimitriwalters.github.io" # the base hostname & protocol for your site
twitter_username: dimitriwalters
github_username:  dimitriwalters

# Google cse -> read the README.md for learn more.
gcse: 015239266043573038855:iqblmapzhiu

# Conversion
markdown:    kramdown

# Outputting
relative_permalinks: false
permalink:     /articles/:title.html
timezone:      Asia/Jakarta

# Markdown Processors
kramdown:
   input: GFM

# Exclude file
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - bower_components
  - node_modules
  - vendor
